name: Go Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Download dependencies
        run: go mod download -x

      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          flags: unittests
          verbose: true

  integration_tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            install_keepassxc: |
              sudo add-apt-repository -y ppa:phoerious/keepassxc
              sudo apt-get update
              sudo apt-get install keepassxc=2.7.\* xserver-xorg-video-dummy x11-apps
              Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile /tmp/xdummy.log -config $(pwd)/hack/xorg_dummy.conf :1 &
              mkdir -p $HOME/xdg-run
              echo "XDG_RUNTIME_DIR=$HOME/xdg-run" >> $GITHUB_ENV
              echo "DISPLAY=:1" >> $GITHUB_ENV
              echo "DOCKER_CREDENTIAL_KEEPASSXC_ASKPASS=echo" >> $GITHUB_ENV
          - os: macos-latest
            install_keepassxc: |
              wget https://raw.githubusercontent.com/caskroom/homebrew-cask/62f1c5430c7280295b32e8aedbac49e152243b4e/Casks/keepassxc.rb
              brew install --cask keepassxc.rb
              echo "KEEPASSXC_EXECUTABLE=/Applications/KeePassXC.app/Contents/MacOS/KeePassXC" >> $GITHUB_ENV
          - os: windows-latest
            install_keepassxc: |
              choco install keepassxc --version=2.7.0
              echo "KEEPASSXC_EXECUTABLE=C:\Program Files\KeePassXC\KeePassXC.exe" >> "$env:GITHUB_ENV"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Download dependencies
        run: go mod download -x

      - name: Download dependencies (dockercred)
        working-directory: dockercred
        run: go mod download -x

      - name: Install KeepassXC
        run: ${{ matrix.install_keepassxc }}

      - name: Test
        run: go test -race -coverprofile='coverage.txt' -covermode=atomic -tags=integration -run='.*_Integration$' -count=1 ./...

      - name: Test (dockercred)
        working-directory: dockercred
        run: go test -race -coverprofile='coverage.txt' -covermode=atomic -tags=integration -run='.*_Integration$' -count=1 ./...

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt,./dockercred/coverage.txt
          flags: integrationtests
          verbose: true
